nome_usuario = input ("Digite seu nome: ")
email_usuario = input ("Digite seu email: ")
numero_usuario = input ("Digite seu telefone: ")
print("----------------------")
print("---Dados do usuário---")
print("----------------------")
print("                      ")
print("Nome: ", nome_usuario)
print("Email: ", email_usuario)
print("Telefone: ", numero_usuario)
print("                      ")
print("Obrigado pelas informações, ", nome_usuario,". Tenha uma boa tarde!")
